export const LECTURE_WAS_UPDATED = 'LECTURE_WAS_UPDATED'
export const LECTURE_WAS_REMOVED = 'LECTURE_WAS_REMOVED'

export const PARTICIPANT_JOINED = 'PARTICIPANT_JOINED'
export const PARTICIPANT_LEFT = 'PARTICIPANT_LEFT'
