export const MESSAGE_WAS_SENT = 'MESSAGE_WAS_SENT'

export const GROUP_MEMBER_JOINED = 'GROUP_MEMBER_JOINED'
export const GROUP_MEMBER_LEFT = 'GROUP_MEMBER_LEFT'

export const GROUP_WAS_UPDATED = 'GROUP_WAS_UPDATED'
